### ISSUE TITLE
Heroku Deployment error

### ISSUE THREAD

**Issue by VicDebonne** [VicDebonne/opdracht2#8]
Wanneer is mijn Strapi Backend op Heroku wil uploaden lukt dit niet. Zowel niet via Heroku Git als Github. 

Alle Heroku commands die ik uitvoer krijg ik dezelfde foutmelding. (Zie bijlage)

<img width="667" alt="Screenshot 2021-04-29 at 18 23 52" src="https://user-images.githubusercontent.com/56590672/116586735-13b7f980-a91a-11eb-980f-2833c3598757.png">

<img width="986" alt="Screenshot 2021-04-29 at 18 23 58" src="https://user-images.githubusercontent.com/56590672/116586742-1581bd00-a91a-11eb-8cbc-1739bd8fbfbc.png">

Updaten van Heroku heeft geen effect. Enig idee waar dit probleem zich bevindt?

**Comment by benoitboucart** [comment]
Helpt het om dit uit te voeren?

```heroku plugins:update```

En indien dit ook niet werkt, dit nog eens proberen: ```heroku update```

zie
https://github.com/heroku/heroku-cli-addons-admin/issues/44

**Comment by VicDebonne** [comment]
Nee! Probeerde ik eerder ook al. Zelf wanneer ik dit uitvoer krijg ik diezelfde foutmelding.

**Comment by benoitboucart** [comment]
En wat krijg je als foutmelding als je deployt via GitHub (1e tabblad, "deploy bij push op master/main")? Kan je de logs op Heroku hier kopieëren/plakken?

Kan je ook een link van je GitHub project van Strapi eens delen?

**Comment by VicDebonne** [comment]
Heb het nu nog eens gedeployt via Github zelf. 
**Link Github project Strapi:** [https://github.com/VicDebonne/opdracht2-backend.git](https://github.com/VicDebonne/opdracht2-backend.git)

Wanneer ik de applicatie open is het gewoon een Application error. "heroku logs --tail" is geen optie omdat ik dan terug dezelfde foutmelding krijg.

**En dit zijn de logs op Heroku zelf:**

>  2021-04-29T17:22:06.214224+00:00 app[web.1]: npm ERR! 
> 2021-04-29T17:22:06.214329+00:00 app[web.1]: npm ERR! Failed at the opdracht-2-backend@0.1.0 start script.
> 2021-04-29T17:22:06.214422+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 2021-04-29T17:22:06.223481+00:00 app[web.1]: 
> 2021-04-29T17:22:06.223741+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
> 2021-04-29T17:22:06.223923+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-29T17_22_06_215Z-debug.log
> 2021-04-29T17:22:06.278809+00:00 heroku[web.1]: Process exited with status 1
> 2021-04-29T17:22:06.369580+00:00 heroku[web.1]: State changed from starting to crashed
> 2021-04-29T17:23:34.874505+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=vic-opdracht2.herokuapp.com request_id=7b0e8c4a-a1fc-4d08-942e-22d19dc47145 fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https
> 2021-04-29T17:23:35.117803+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=vic-opdracht2.herokuapp.com request_id=44dc6310-3093-40ab-91fa-12452efdfcfa fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https

**Comment by benoitboucart** [comment]
Heeft Heroku de buildpack `heroku/nodejs` toegevoegd. Heb je die niet? Voeg die manueel toe en deploy dan opnieuw (door een nieuwe push op master / main te forceren).

**Comment by VicDebonne** [comment]
Helaas is dat het probleem niet. 

_heroku/node_ stond al bij _buildpacks_. Ik heb ze dan toch eens verwijderd, opnieuw toegevoegd, opnieuw gepusht en gedeployt, maar niets is veranderd! (nog steeds _Application error_ en dezelfde _Application Logs_)

<img width="1317" alt="Screenshot 2021-04-29 at 19 53 36" src="https://user-images.githubusercontent.com/56590672/116596807-2552ce80-a925-11eb-945b-d80e699d656b.png">

**Comment by benoitboucart** [comment]
Dag Vic,

Ik heb net een Fork van je project gemaakt en zelf gedeployt zonder problemen.

Ik raad je aan om een nieuw project aan te maken op Heroku & de tutorial van de video tutorial op leho te volgen (of DeNaald.md file van tijdens de laboles). Als het dan nog niet werkt, probeer eens met een fork van je eigen repo.

Zorg ook zeker dat je de database instellingen (Combell) ook in Heroku goed instelt.

![image](https://user-images.githubusercontent.com/1086264/116597993-96df4c80-a926-11eb-9fc9-371b1ef24ba9.png)

![image](https://user-images.githubusercontent.com/1086264/116598024-a199e180-a926-11eb-97f6-e88c1d35e328.png)

![image](https://user-images.githubusercontent.com/1086264/116598149-c9894500-a926-11eb-885a-b80ced8edbbd.png)


Succes

**Comment by VicDebonne** [comment]
Excuses voor het heropenen van de issue! 

De zaken die je hier aanhaalt, ben ik de laatste dagen al meermaals doorgegaan.

Maar zou het probleem niet ergens in mijn **Heroku instellingen** kunnen zitten? Is het een optie om op de een of andere manier alles van Heroku van mijn laptop te verwijderen, en deze helemaal opnieuw in te stellen? (eerst alles kunnen verwijderen en dan `$ brew tap heroku/brew && brew install heroku` en opnieuw inloggen enzo.) (wel raar want in het verleden heb ik hier nooit last van gehad)

Of zou het probleem hier echt niet kunnen zitten? Dan probeer ik gewoon nog een paar keer hetzelfde en blijf ik de tutorial volgen!

**Comment by benoitboucart** [comment]
Je mag lokaal je Heroku gerust eens verwijderen en opnieuw installeren. Maar deployen via GitHub heeft geen enkel invloed op wat je online hebt staan (= want ik kon je project deployen via een fork van jouw GitHub). Daarom dat ik ook voorstelde om eens je code in een nieuwe GitHub te zetten en opnieuw te proberen.

Als je denkt dat het aan je Heroku instellingen zelf ligt, dan kan je dit checken door eens een nieuw Heroku account aan te maken.

Laat je weten indien het lukt?

**Comment by VicDebonne** [comment]
Door alles van Heroku lokaal te verwijderen en te herinstalleren (en een nieuw acc), kan ik nu terug alle commands uitvoeren omtrent Heroku. 

Heb nog enkele keren from scratch gedeployd (Zowe via Heroku Git als Github). De connectie met database dubbel gecheckt, npm en node geupdate, maar heb nog steeds dezelfde error:
```
2021-04-29T23:06:24.546232+00:00 app[web.1]: npm ERR! Failed at the opdracht-2-backend@0.1.0 start script.
2021-04-29T23:06:24.546390+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-29T23:06:24.556440+00:00 app[web.1]: 
2021-04-29T23:06:24.556677+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-04-29T23:06:24.556804+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-29T23_06_24_547Z-debug.log
2021-04-29T23:06:24.603061+00:00 heroku[web.1]: Process exited with status 1
2021-04-29T23:06:24.666757+00:00 heroku[web.1]: State changed from starting to crashed
2021-04-29T23:06:29.000000+00:00 app[api]: Build succeeded
2021-04-29T23:08:39.108940+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=vic-dev2-opdracht2.herokuapp.com request_id=d4932dc7-187b-4606-8529-582b6caf6cae fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https
2021-04-29T23:08:39.384596+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=vic-dev2-opdracht2.herokuapp.com request_id=bde2a364-6fc6-479b-82d9-abe7f3e65611 fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https
```

Ik heb ook nog eens Denaald gedoployd. En zelf daar krijg ik ook diezelfde error...

**Comment by VicDebonne** [comment]
```
2021-04-30T09:26:32.578993+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-04-30T09:26:32.579170+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-30T09_26_32_559Z-debug.log
2021-04-30T09:26:32.673315+00:00 heroku[web.1]: Process exited with status 1
2021-04-30T09:26:32.766078+00:00 heroku[web.1]: State changed from starting to crashed
2021-04-30T09:26:32.811820+00:00 heroku[web.1]: State changed from crashed to starting
2021-04-30T09:26:56.027456+00:00 heroku[web.1]: Starting process with command `npm start`
2021-04-30T09:27:00.422729+00:00 app[web.1]: 
2021-04-30T09:27:00.422747+00:00 app[web.1]: > opdracht-2-backend@0.1.0 start /app
2021-04-30T09:27:00.422748+00:00 app[web.1]: > strapi start
2021-04-30T09:27:00.422748+00:00 app[web.1]: 
2021-04-30T09:27:14.398008+00:00 app[web.1]: [2021-04-30T09:27:14.397Z] debug ⛔️ Server wasn't able to start properly.
2021-04-30T09:27:14.399323+00:00 app[web.1]: [2021-04-30T09:27:14.399Z] error Error: connect ETIMEDOUT
2021-04-30T09:27:14.399325+00:00 app[web.1]:     at Connection._handleConnectTimeout (/app/node_modules/mysql/lib/Connection.js:409:13)
2021-04-30T09:27:14.399325+00:00 app[web.1]:     at Object.onceWrapper (events.js:421:28)
2021-04-30T09:27:14.399326+00:00 app[web.1]:     at Socket.emit (events.js:315:20)
2021-04-30T09:27:14.399326+00:00 app[web.1]:     at Socket._onTimeout (net.js:483:8)
2021-04-30T09:27:14.399326+00:00 app[web.1]:     at listOnTimeout (internal/timers.js:554:17)
2021-04-30T09:27:14.399326+00:00 app[web.1]:     at processTimers (internal/timers.js:497:7)
2021-04-30T09:27:14.399327+00:00 app[web.1]:     --------------------
2021-04-30T09:27:14.399328+00:00 app[web.1]:     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2021-04-30T09:27:14.399328+00:00 app[web.1]:     at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
2021-04-30T09:27:14.399329+00:00 app[web.1]:     at Connection.connect (/app/node_modules/mysql/lib/Connection.js:116:18)
2021-04-30T09:27:14.399329+00:00 app[web.1]:     at /app/node_modules/knex/lib/dialects/mysql/index.js:68:18
2021-04-30T09:27:14.399330+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-04-30T09:27:14.399330+00:00 app[web.1]:     at Client_MySQL.acquireRawConnection (/app/node_modules/knex/lib/dialects/mysql/index.js:63:12)
2021-04-30T09:27:14.399331+00:00 app[web.1]:     at create (/app/node_modules/knex/lib/client.js:290:39)
2021-04-30T09:27:14.420962+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-04-30T09:27:14.421533+00:00 app[web.1]: npm ERR! errno 1
2021-04-30T09:27:14.428944+00:00 app[web.1]: npm ERR! opdracht-2-backend@0.1.0 start: `strapi start`
2021-04-30T09:27:14.429183+00:00 app[web.1]: npm ERR! Exit status 1
2021-04-30T09:27:14.429428+00:00 app[web.1]: npm ERR! 
2021-04-30T09:27:14.429674+00:00 app[web.1]: npm ERR! Failed at the opdracht-2-backend@0.1.0 start script.
2021-04-30T09:27:14.429845+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-30T09:27:17.037354+00:00 app[web.1]: 
2021-04-30T09:27:17.038090+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-04-30T09:27:17.038401+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-04-30T09_27_14_430Z-debug.log
2021-04-30T09:27:17.129619+00:00 heroku[web.1]: Process exited with status 1
2021-04-30T09:27:17.253433+00:00 heroku[web.1]: State changed from starting to crashed
2021-04-30T09:27:19.711295+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=vic-dev2-opdracht2.herokuapp.com request_id=25df373c-bb2c-4677-95f0-ff6633534030 fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https
2021-04-30T09:27:21.000000+00:00 app[api]: Build succeeded
2021-04-30T09:27:31.561807+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=vic-dev2-opdracht2.herokuapp.com request_id=2cf896ba-37d7-4e35-a4ff-8a6f0364ee6d fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https
2021-04-30T09:27:31.973537+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=vic-dev2-opdracht2.herokuapp.com request_id=b6b82a3d-97e9-4ea3-88f5-2534db0edd79 fwd="178.119.185.117" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by benoitboucart** [comment]
'DATABASE_PORT' op Heroku op 3306 zetten
